name: Deployment

on:
  push:
    branches:
      - dev
      - mod
      - prod

jobs:
    deploy:
        environment: ${{ github.ref_name }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Print environment
              run: echo ${{ github.ref_name }}