name: Deployment

on:
  pull_request:
    branches:
      - dev
      - mod
      - prod

jobs:
    deploy:
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true 
        environment: ${{ github.ref_name }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Print environment
              run: echo ${{ github.ref_name }}